#!/bin/sh
#
# Capture test data from local system.

# cgroupfs parser
mkdir -p cgroupfs
/usr/bin/env sudo find /sys/fs/cgroup/cpuacct/ -printf "\n%p\n" -exec cat {} 2>/dev/null \; > cgroupfs/cpuacct
/usr/bin/env sudo find /sys/fs/cgroup/memory/ -printf "\n%p\n" -exec cat {} 2>/dev/null \; > cgroupfs/memory
/usr/bin/env sudo find /sys/fs/cgroup/blkio/ -printf "\n%p\n" -exec cat {} 2>/dev/null \; > cgroupfs/blkio

# ps parser
mkdir -p ps
/usr/bin/env sudo docker ps -a -s --no-trunc --format "{{.ID}}|{{.Status}}|{{.Size}}" 2>/dev/null > ps/ps

